apiVersion: v1 
kind: ConfigMap
metadata:
   namespace: roboshop
   name: shipping
   labels:
     project: roboshop
     component: shipping
     tier: backend
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
      
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  namespace: roboshop
  name: shipping
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
     containers:
     - name: shipping
       image: srinunaik208/shipping:v2 
       envFrom:
       - configMapRef:
          name: shipping

---
apiVersion: v1 
kind: Service 
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70


     
      
        